### base config ###
full_field: &FULL_FIELD
  run_num: "00"
  exper_path: "outputs/alaska"
  data_path: "data/alaska/slip_potency_smooth"
  fault_path: "data/alaska/fault"
  tremor_path: "data/alaska/tremor"
  llh_path: "data/alaska/fault/llh"
  mean_path: "data/alaska/norm_value/mean.npy"
  std_path: "data/alaska/norm_value/std.npy"
  device: "cuda"
  use_tremor: !!bool False
  early_stopping_patience: 20
  batch_size: 54
  dt: 1
  lr:  0.00001
  max_epochs: 100
  img_size: 2556
  patch_size: 3
  fea_len: 2556
  time_chans: 2
  data_chans: 3
  out_chans: 3

# 训练基础模型
backbone: &backbone
  <<: *FULL_FIELD
  run_num: "00"
  two_step_training: !!bool False
  checkpoint_path: "outputs/alaska/00/training_checkpoints/backbone.ckpt"
  best_checkpoint_path: "outputs/alaska/00/training_checkpoints/best_model.ckpt"
  writer: "outputs/alaska/00/tensorboard"

# 微调迭代的基础模型
finetune: &finetune
  <<: *backbone
  run_num: "11"
  lr:  1e-5
  max_epochs: 30
  batch_size: 16
  pretrained: !!bool True
  two_step_training: !!bool True
  pretrained_ckpt_path: "outputs/alaska/00/training_checkpoints/backbone.ckpt"
  checkpoint_path: "outputs/alaska/11/training_checkpoints/backbone.ckpt"
  best_checkpoint_path: "outputs/alaska/11/training_checkpoints/best_model.ckpt"
  writer: "outputs/alaska/11/tensorboard"


# backbone_fivedays: 
#   <<: *FULL_FIELD
#   run_num: "33"
#   dt: 5
#   two_step_training: !!bool False
#   checkpoint_path: "outputs/alaska/33/training_checkpoints/backbone.ckpt"
#   best_checkpoint_path: "outputs/alaska/33/training_checkpoints/best_model.ckpt"
#   writer: "outputs/alaska/33/tensorboard"