_defaults: &defaults
  exper_path: "outputs/alaska"
  data_path: "data/alaska/slip_potency_smooth"
  mean_path: "data/alaska/norm_value/mean.npy"
  std_path: "data/alaska/norm_value/std.npy"
  device: "cuda"
  use_tremor: false
  early_stopping_patience: 20
  batch_size: 16
  lr: 1.0e-5
  max_epochs: 30
  patch_size: 3
  fea_len: 2556
  time_chans: 2
  data_chans: 3

backbone:
  <<: *defaults
