_defaults: &defaults
  exper_path: "outputs/cascadia"
  data_path: "data/cascadia/slip_potency_smooth"
  mean_path: "data/cascadia/norm_value/mean.npy"
  std_path: "data/cascadia/norm_value/std.npy"
  device: "cuda"
  use_tremor: false
  early_stopping_patience: 40
  batch_size: 16
  lr: 8.0e-4
  max_epochs: 100
  patch_size: 3
  fea_len: 3339
  time_chans: 2
  data_chans: 3

backbone:
  <<: *defaults
