_defaults: &defaults
  exper_path: "outputs/nankai"
  data_path: "data/nankai/slip_potency_smooth"
  mean_path: "data/nankai/norm_value/mean.npy"
  std_path: "data/nankai/norm_value/std.npy"
  device: "cuda"
  use_tremor: false
  early_stopping_patience: 5
  batch_size: 16
  lr: 8.0e-4
  max_epochs: 30
  patch_size: 3
  fea_len: 2943
  time_chans: 2
  data_chans: 3

backbone:
  <<: *defaults
