_defaults: &defaults
  exper_path: "outputs/newzealand"
  data_path: "data/newzealand/slip_potency_smooth"
  mean_path: "data/newzealand/norm_value/mean.npy"
  std_path: "data/newzealand/norm_value/std.npy"
  device: "cuda"
  use_tremor: false
  early_stopping_patience: 20
  batch_size: 16
  lr: 2.0e-4
  max_epochs: 30
  patch_size: 3
  fea_len: 3315
  time_chans: 2
  data_chans: 3

backbone:
  <<: *defaults
